<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "debts".
 *
 * @property int $id
 * @property string|null $street_and_num
 * @property string|null $debt
 * @property int|null $date_last_update
 */
class Debts extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'debts';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date_last_update'], 'integer'],
            [['street_and_num', 'debt', 'historyPayModel'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'street_and_num' => 'Улица и номер участка',
            'debt' => 'Сумма долга',
            'date_last_update' => 'Последнее обновление'
        ];
    }
    public function saveImage($filename)
    {
        $this->street_and_num = $filename;
        return $this->save(false);
    }

    public function getImage()
    {
        return ($this->street_and_num) ? 'uploads/' . $this->street_and_num : '/img/sad.png';
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpLoad();
        $imageUploadModel->deleteCurrentImage($this->street_and_num);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
	public function saveDebts()
    {
            return $this->save();
    }
}
