<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "gas".
 *
 * @property int $id
 * @property string|null $street_and_num
 * @property string|null $sum
 * @property string|null $additionally
 * @property string|null $gas_insurance
 */
class Gas extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'gas';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['street_and_num', 'sum', 'additionally', 'gas_insurance'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'street_and_num' => 'Адрес',
            'sum' => 'Сумма за газ',
            'additionally' => 'Дополнительно',
            'gas_insurance' => 'Платеж за страхование газа'
        ];
    }

    
    public function saveImage($filename)
    {
        $this->street_and_num = $filename;
        return $this->save(false);
    }

    public function getImage()
    {
        return ($this->street_and_num) ? 'uploads/' . $this->street_and_num : '/img/sad.png';
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpLoad();
        $imageUploadModel->deleteCurrentImage($this->street_and_num);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
	public function saveDebts()
    {
            return $this->save();
    }
}
