<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $title
 * @property string|null $content
 * @property string|null $photo
 * @property string|null $author
 * @property int|null $like
 * @property int|null $views
 * @property int|null $date
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['like', 'views'], 'integer'],
            [['name', 'title', 'photo', 'author'], 'string', 'max' => 255],
            [['content'], 'string', 'max' => 500],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название новости',
            'title' => 'Заголовок',
            'content' => 'Содержание',
            'photo' => 'Фото',
            'author' => 'Автор',
            'like' => 'лайки',
            'views' => 'Новая(0) или старая(1) новость',
            'date' => 'Дата',
        ];
    }

    public function saveImage($filename)
    {
        $this->photo = $filename;
        return $this->save(false);
    }

    public function getImage()
    {
        return ($this->photo) ? '../uploads/' . $this->photo : '../img/empty.png';
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpLoad();
        $imageUploadModel->deleteCurrentImage($this->photo);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function saveNews()
    {
        $userModel = User::find()->where(['id' => Yii::$app->user->identity->id])->one();
        $this->author = $userModel->name;
            return $this->save(false);
    }
}



