<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "protocols".
 *
 * @property int $id
 * @property string|null $title
 * @property string|null $description
 * @property string|null $photo
 * @property int|null $date
 */
class Protocols extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'protocols';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date'], 'integer'],
            [['title', 'description', 'photo'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'description' => 'Описание',
            'photo' => 'Название файла в pdf',
            'date' => 'Дата',
        ];
    }

    public function saveImage($filename)
    {
        $this->photo = $filename;
        return $this->save(false);
    }

    public function getImage()
    {
        return ($this->photo) ? '/uploads/' . $this->photo : '/img/sad.png';
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpLoad();
        $imageUploadModel->deleteCurrentImage($this->photo);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
