<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "smeta".
 *
 * @property int $id
 * @property string|null $title
 * @property string|null $description
 * @property string|null $file
 * @property int|null $date
 */
class Smeta extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'smeta';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date'], 'integer'],
            [['title', 'description', 'file'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'description' => 'Описание',
            'file' => 'Название файла',
            'date' => 'Дата',
        ];
    }

    public function saveImage($filename)
    {
        $this->file = $filename;
        return $this->save(false);
    }

    public function getImage()
    {
        return ($this->file) ? '/uploads/' . $this->file : '/img/sad.png';
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpLoad();
        $imageUploadModel->deleteCurrentImage($this->file);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
	public function saveSmeta()
    {
            return $this->save(false);
    }
}
